[METADATA]
modified = "2026-07-01"

[[PRINCIPALS]]
name = "Steven J. Morris"
email = "sjmorris.dlore@gmail.com"

[[ACCOUNTS]]
address = "rwU5e8C8sBjgDfuYwLGwTe9zAnf5TYxrsn"
desc = "Eigenthrope NFT vault — issues participation and winner artifacts for the Eigenthrope interactive story on eigenthrope.sjmorriswrites.com"
